title: Cut
short_title: cut.social
description: "A blog on psychology, experiment design tools, and other things"
baseurl: ""
url: ""
theme: minima
minima:
  skin: dark
  social_links:
    twitter: salarrad
show_excerpts: true
header_pages:
  - index.md
  - demo.md
  - blog.md
  - about.md
  - cv.md
collections:
  - members
plugins:
  - jekyll-pdf-embed
disqus:
  shortname: <cut-social>

